version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: musicalia 
  frontend:
    build: ./frontend
    ports:
      - 4200:80
    restart: unless-stopped

  backend:
    build: ./backend
    
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: unless-stopped